### ISSUE TITLE
Cannot read property 'iterator' of undefined

### ISSUE THREAD

**Issue by tiansin** [enniel/adonis-notifications#2]
```
    this.app.bind('Adonis/Notifications/DatabaseNotification', () => {
      return require('../src/DatabaseNotification')
    })
    this.app.alias('Adonis/Notifications/DatabaseNotification', 'DatabaseNotification')
```

When the DatabaseNotification model is initialized, the _bootIfNotBooted method is not called and an error is reported.

https://github.com/adonisjs/adonis-lucid/blob/2646b0c8abd74bd0e198bd10b03bcd4812056033/src/Lucid/QueryBuilder/index.js#L153

**Comment by enniel** [comment]
@tiansin Thanks! Fixed in version 1.2.2.

**Comment by yanataranets** [comment]
Hello!
I still have this error and can't find solution

**Comment by Hecroesmo** [comment]
how did you solve this issue?
